<?php

namespace Omnipay\Chekonline\Message;

/**
 * Class ComplexResponse
 * @package Omnipay\Chekonline\Message
 */
class ComplexResponse extends AbstractResponse
{
    /**
     * Is the response successful?
     *
     * @return boolean
     */
    public function isSuccessful()
    {
        return $this->getCode() === 0;
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     *
     * @return string
     */
    public function getTransactionId()
    {
        return $this->getData()['FiscalDocNumber'];
    }
}
